name: 发布在线教材

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 取回教材仓库
        uses: actions/checkout@v4
      - name: 配置 Pages
        uses: actions/configure-pages@v5
      - name: 上传静态教材
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 部署
        id: deployment
        uses: actions/deploy-pages@v4
